production:
  adapter: sqlite3
  database: db/grocerytracker_production.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/grocerytracker_test.sqlite3
  pool: 5
  timeout: 5000
